export const flashcards = [
  { id: 1, type: "definition_to_term", question: "Accélération du rythme cardiaque", answer: "Tachycardie" },
  { id: 2, type: "term_to_definition", question: "Bradycardie", answer: "Ralentissement du rythme cardiaque" },
  { id: 3, type: "definition_to_term", question: "Difficulté à respirer", answer: "Dyspnée" },
  { id: 4, type: "term_to_definition", question: "Hypertension", answer: "Pression artérielle élevée" },
  { id: 5, type: "term_to_definition", question: "Hypotension", answer: "Pression artérielle basse" },

  { id: 6, type: "definition_to_term", question: "Manque de globules rouges", answer: "Anémie" },
  { id: 7, type: "term_to_definition", question: "Ischémie", answer: "Diminution de l’apport sanguin à un tissu" },
  { id: 8, type: "term_to_definition", question: "Infarctus du myocarde", answer: "Nécrose du muscle cardiaque" },
  { id: 9, type: "definition_to_term", question: "Douleur thoracique d’origine cardiaque", answer: "Angine de poitrine" },
  { id: 10, type: "term_to_definition", question: "AVC", answer: "Accident vasculaire cérébral" },

  { id: 11, type: "definition_to_term", question: "Inflammation du foie", answer: "Hépatite" },
  { id: 12, type: "term_to_definition", question: "Gastrite", answer: "Inflammation de l’estomac" },
  { id: 13, type: "term_to_definition", question: "Appendicite", answer: "Inflammation de l’appendice" },
  { id: 14, type: "definition_to_term", question: "Inflammation des bronches", answer: "Bronchite" },
  { id: 15, type: "term_to_definition", question: "Pneumonie", answer: "Infection des poumons" },

  { id: 16, type: "definition_to_term", question: "Taux de sucre élevé dans le sang", answer: "Hyperglycémie" },
  { id: 17, type: "definition_to_term", question: "Taux de sucre bas dans le sang", answer: "Hypoglycémie" },
  { id: 18, type: "term_to_definition", question: "Diabète de type 2", answer: "Résistance à l’insuline" },
  { id: 19, type: "definition_to_term", question: "Sucre dans les urines", answer: "Glycosurie" },

  { id: 20, type: "term_to_definition", question: "Insuffisance rénale", answer: "Diminution du fonctionnement des reins" },
  { id: 21, type: "definition_to_term", question: "Inflammation du rein", answer: "Néphrite" },
  { id: 22, type: "definition_to_term", question: "Sang dans les urines", answer: "Hématurie" },
  { id: 23, type: "term_to_definition", question: "Protéinurie", answer: "Protéines dans les urines" },

  { id: 24, type: "definition_to_term", question: "Douleur articulaire", answer: "Arthralgie" },
  { id: 25, type: "term_to_definition", question: "Arthrite", answer: "Inflammation d’une articulation" },
  { id: 26, type: "term_to_definition", question: "Ostéoporose", answer: "Fragilisation des os" },
  { id: 27, type: "definition_to_term", question: "Inflammation de l’os", answer: "Ostéite" },

  { id: 28, type: "definition_to_term", question: "Perte de mémoire", answer: "Amnésie" },
  { id: 29, type: "term_to_definition", question: "Épilepsie", answer: "Crises convulsives" },
  { id: 30, type: "definition_to_term", question: "Paralysie d’un côté du corps", answer: "Hémiplégie" },

  { id: 31, type: "term_to_definition", question: "Asthme", answer: "Inflammation chronique des bronches" },
  { id: 32, type: "definition_to_term", question: "Liquide dans les poumons", answer: "Œdème pulmonaire" },
  { id: 33, type: "term_to_definition", question: "Embolie pulmonaire", answer: "Obstruction d’une artère pulmonaire" },

  { id: 34, type: "definition_to_term", question: "Fièvre élevée persistante", answer: "Hyperthermie" },
  { id: 35, type: "term_to_definition", question: "Sepsis", answer: "Infection généralisée grave" },
  { id: 36, type: "definition_to_term", question: "Inflammation de la peau", answer: "Dermatite" },

  { id: 37, type: "term_to_definition", question: "Hypothermie", answer: "Baisse de température corporelle" },
  { id: 38, type: "definition_to_term", question: "Absence de douleur", answer: "Analgésie" },
  { id: 39, type: "term_to_definition", question: "Anesthésie", answer: "Perte de sensibilité" },

  { id: 40, type: "definition_to_term", question: "Douleur musculaire", answer: "Myalgie" },
  { id: 41, type: "term_to_definition", question: "Neuropathie", answer: "Atteinte des nerfs" },
  { id: 42, type: "definition_to_term", question: "Rétrécissement d’un vaisseau", answer: "Sténose" },

  { id: 43, type: "definition_to_term", question: "Mort d’un tissu", answer: "Nécrose" },
  { id: 44, type: "term_to_definition", question: "Infarctus", answer: "Nécrose par obstruction vasculaire" },

  { id: 45, type: "definition_to_term", question: "Inflammation du poumon", answer: "Pneumonie" },
  { id: 46, type: "term_to_definition", question: "Bronchite", answer: "Inflammation des bronches" },
  { id: 47, type: "definition_to_term", question: "Inflammation des sinus", answer: "Sinusite" },

  { id: 48, type: "term_to_definition", question: "Otite", answer: "Inflammation de l’oreille" },
  { id: 49, type: "definition_to_term", question: "Inflammation du cœur", answer: "Cardite" },
  { id: 50, type: "term_to_definition", question: "Endocardite", answer: "Inflammation de l’endocarde" },

  { id: 51, type: "definition_to_term", question: "Réduction du volume d’un organe", answer: "Atrophie" },
  { id: 52, type: "term_to_definition", question: "Hypertrophie", answer: "Augmentation du volume d’un organe" },

  { id: 53, type: "definition_to_term", question: "Présence de sang dans les urines", answer: "Hématurie" },
  { id: 54, type: "term_to_definition", question: "Polyurie", answer: "Augmentation des urines" },

  { id: 55, type: "definition_to_term", question: "Diminution des urines", answer: "Oligurie" },
  { id: 56, type: "term_to_definition", question: "Anurie", answer: "Absence d’urine" },
  { id: 57, type: "definition_to_term", question: "Inflammation des méninges", answer: "Méningite" },
  { id: 58, type: "term_to_definition", question: "Encéphalopathie", answer: "Maladie du cerveau" },
  { id: 59, type: "definition_to_term", question: "Inflammation des nerfs", answer: "Névrite" },
  { id: 60, type: "term_to_definition", question: "Neurologie", answer: "Spécialité médicale du système nerveux" },
  { id: 61, type: "definition_to_term", question: "Tumeur d’un nerf", answer: "Neurinome" },
  { id: 62, type: "term_to_definition", question: "Myélite", answer: "Inflammation de la moelle épinière" },
  { id: 63, type: "definition_to_term", question: "Douleur d’un nerf", answer: "Névralgie" },
  { id: 64, type: "term_to_definition", question: "Psychiatrie", answer: "Spécialité des troubles mentaux" },

  { id: 65, type: "definition_to_term", question: "Inflammation de la vessie", answer: "Cystite" },
  { id: 66, type: "term_to_definition", question: "Néphrologie", answer: "Spécialité médicale des reins" },
  { id: 67, type: "definition_to_term", question: "Calcul dans le rein", answer: "Néphrolithiase" },
  { id: 68, type: "term_to_definition", question: "Urologie", answer: "Spécialité des voies urinaires" },
  { id: 69, type: "definition_to_term", question: "Inflammation de l’urètre", answer: "Urétrite" },
  { id: 70, type: "term_to_definition", question: "Pyélonéphrite", answer: "Infection du rein et du bassinet" },
  { id: 71, type: "definition_to_term", question: "Présence de pus dans les urines", answer: "Pyurie" },
  { id: 72, type: "term_to_definition", question: "Hémodialyse", answer: "Filtration artificielle du sang" },

  { id: 73, type: "definition_to_term", question: "Inflammation des ganglions", answer: "Adénite" },
  { id: 74, type: "term_to_definition", question: "Immunologie", answer: "Étude du système immunitaire" },
  { id: 75, type: "definition_to_term", question: "Déficit du système immunitaire", answer: "Immunodéficience" },
  { id: 76, type: "term_to_definition", question: "Lymphocyte", answer: "Globule blanc impliqué dans l’immunité" },
  { id: 77, type: "definition_to_term", question: "Inflammation d’un ganglion lymphatique", answer: "Lymphadénite" },
  { id: 78, type: "term_to_definition", question: "Splénomégalie", answer: "Augmentation du volume de la rate" },
  { id: 79, type: "definition_to_term", question: "Tumeur du système lymphatique", answer: "Lymphome" },
  { id: 80, type: "term_to_definition", question: "Leucocytose", answer: "Augmentation des globules blancs" },

  { id: 81, type: "definition_to_term", question: "Inflammation du vagin", answer: "Vaginite" },
  { id: 82, type: "term_to_definition", question: "Gynécologie", answer: "Spécialité médicale de l’appareil génital féminin" },
  { id: 83, type: "definition_to_term", question: "Inflammation de l’utérus", answer: "Métrite" },
  { id: 84, type: "term_to_definition", question: "Hystérectomie", answer: "Ablation chirurgicale de l’utérus" },
  { id: 85, type: "definition_to_term", question: "Douleur des règles", answer: "Dysménorrhée" },
  { id: 86, type: "term_to_definition", question: "Aménorrhée", answer: "Absence de menstruations" },
  { id: 87, type: "definition_to_term", question: "Inflammation des ovaires", answer: "Ovarite" },
  { id: 88, type: "term_to_definition", question: "Mammographie", answer: "Radiographie du sein" },

  { id: 89, type: "definition_to_term", question: "Inflammation de la prostate", answer: "Prostatite" },
  { id: 90, type: "term_to_definition", question: "Orchidectomie", answer: "Ablation chirurgicale d’un testicule" },
  { id: 91, type: "definition_to_term", question: "Douleur du testicule", answer: "Orchialgie" },
  { id: 92, type: "term_to_definition", question: "Hypertrophie bénigne de la prostate", answer: "Augmentation non cancéreuse du volume prostatique" },
  { id: 93, type: "definition_to_term", question: "Inflammation du gland", answer: "Balanite" },
  { id: 94, type: "term_to_definition", question: "Cryptorchidie", answer: "Absence de descente d’un testicule" },
  { id: 95, type: "definition_to_term", question: "Présence de spermatozoïdes dans les urines", answer: "Spermaturie" },
  { id: 96, type: "term_to_definition", question: "Vasectomie", answer: "Section des canaux déférents" },

  { id: 97, type: "definition_to_term", question: "Inflammation du côlon", answer: "Colite" },
  { id: 98, type: "term_to_definition", question: "Gastroentérologie", answer: "Spécialité de l’appareil digestif" },
  { id: 99, type: "definition_to_term", question: "Inflammation du pancréas", answer: "Pancréatite" },
  { id: 100, type: "term_to_definition", question: "Hépatomégalie", answer: "Augmentation du volume du foie" },
  { id: 101, type: "definition_to_term", question: "Inflammation de l’intestin", answer: "Entérite" },
  { id: 102, type: "term_to_definition", question: "Rectorragie", answer: "Saignement provenant du rectum" },
  { id: 103, type: "definition_to_term", question: "Difficulté à avaler", answer: "Dysphagie" },
  { id: 104, type: "term_to_definition", question: "Gastrectomie", answer: "Ablation partielle ou totale de l’estomac" },

  { id: 105, type: "definition_to_term", question: "Inflammation de la trachée", answer: "Trachéite" },
  { id: 106, type: "term_to_definition", question: "Pneumologie", answer: "Spécialité médicale des poumons" },
  { id: 107, type: "definition_to_term", question: "Inflammation de la plèvre", answer: "Pleurésie" },
  { id: 108, type: "term_to_definition", question: "Bronchoscopie", answer: "Examen visuel des bronches" },
  { id: 109, type: "definition_to_term", question: "Présence d’air dans la plèvre", answer: "Pneumothorax" },
  { id: 110, type: "term_to_definition", question: "Laryngite", answer: "Inflammation du larynx" },
  { id: 111, type: "definition_to_term", question: "Ablation d’un poumon", answer: "Pneumonectomie" },
  { id: 112, type: "term_to_definition", question: "Hémoptysie", answer: "Crachat de sang provenant des voies respiratoires" },

  { id: 113, type: "definition_to_term", question: "Inflammation des bronchioles", answer: "Bronchiolite" },
  { id: 114, type: "term_to_definition", question: "Rhinite", answer: "Inflammation de la muqueuse nasale" },
  { id: 115, type: "definition_to_term", question: "Respiration rapide", answer: "Polypnée" },
  { id: 116, type: "term_to_definition", question: "Apnée", answer: "Arrêt temporaire de la respiration" }
];